/*
	BASIC MEMBER INFO
*/
CREATE TABLE MEMBER_INFO
(
	IDX		INT PRIMARY KEY IDENTITY(1,1),		-- PK
	USERID	VARCHAR(50) NOT NULL,				-- ID
	PWD		VARCHAR(500) NOT NULL,				-- PASSWORD
	NAME	VARCHAR(30)	NOT NULL,				-- NAME
	TELL	VARCHAR(30),						-- PHONE
	EMAIL	VARCHAR(150),						-- EMAIL
	ADDR	VARCHAR(150),						-- ADDRESS
	ISSMS	VARCHAR(1),							-- SMS SEND (Y :YES, N: NO)
	ISEMAIL	VARCHAR(1),							-- EMAIL SEND (Y :YES, N: NO)
	INDT	DATETIME DEFAULT(GETDATE()),		-- CREATE DATE
	UPDT	DATETIME							-- UPDATE DATE
)

/*
 MEMBER PAY INFO
*/
CREATE TABLE MEMBER_PAYINFO
(
	IDX		INT PRIMARY KEY IDENTITY(1,1),		-- PK
	USERID	VARCHAR(50) NOT NULL,				-- ID
	PTYPE	VARCHAR(1)	NOT NULL,				-- PAY TYPE (S: SUCESS, C: CANCLE, P: Promo code, R:카드)
	PRICE	FLOAT		NOT NULL,				-- PRICE
	SDATE	DATETIME	NOT NULL,				-- START DATE
	EDATE	DATETIME	NOT NULL,				-- END DATE
	ISUSE	VARCHAR(1)	NOT NULL,				-- USE (Y,N)
	INDT	DATETIME DEFAULT(GETDATE())			-- CREATE DATE
)


/*
LOGIN HISTORY
*/
CREATE TABLE MEMBER_LOGIN
(
	IDX		INT PRIMARY KEY IDENTITY(1,1),		-- PK
	USERID	VARCHAR(50) NOT NULL,				-- ID
	IP		VARCHAR(20),						-- IP
	AGENT	VARCHAR(MAX),						-- AGENT
	INDT	DATETIME DEFAULT(GETDATE())			-- CREATE DATE
)

/*
CATEGORY INFO TOP
*/
CREATE TABLE CATEGORY_INFO
(
	TC_IDX		INT PRIMARY KEY IDENTITY(1,1),		-- PK
	NAME	VARCHAR(100) NOT NULL,					-- CATEGORY NAME
	INDT	DATETIME DEFAULT(GETDATE())				-- CREATE DATE
)

/*
CATEGORY INFO BOTTOM
*/
CREATE TABLE CATEGORY_INFO1
(
	BC_IDX		INT PRIMARY KEY IDENTITY(1,1),		-- PK
	TC_IDX		INT NOT NULL,						-- TOP CATEGORY
	NAME		VARCHAR(100) NOT NULL,				-- CATEGORY NAME
	INDT		DATETIME DEFAULT(GETDATE())			-- CREATE DATE
)
/*
Product Info
*/
CREATE TABLE PRODUCT_INFO
(
	PR_IDX		INT PRIMARY KEY IDENTITY(1,1),	-- PK
	BC_IDX		INT,							-- CATEGORY
	PR_NAME		VARCHAR(100) NOT NULL,			-- NAME
	PR_COUNTRY	VARCHAR(100) NOT NULL,			-- 구가
	PR_GUBUN	VARCHAR(100),					-- 구분
	PR_QTY		INT,							-- 본수
	PR_LITER	INT,							-- 용량
	PR_INCOME	VARCHAR(100),					-- 수입사
	PR_IN_PRICE FLOAT,							-- 공급가
	PR_PRICE	FLOAT		 NOT NULL,			-- PRICE
	PR_SALE		FLOAT,							-- SALE PRICE
	ISSALE		VARCHAR(1)	NOT NULL,			-- SALE
	PR_WEIGHT	FLOAT,							-- LITER
	PE_DESC		VARCHAR(MAX),					-- DESCRIPTION
	INDT		DATETIME DEFAULT(GETDATE())		-- CREATE DATE
)

/*
ORDER INFO
*/
CREATE TABLE ORDER_INFO
(
	OR_IDX			VARCHAR(10) PRIMARY KEY,		-- PK
	USERID			VARCHAR(50) NOT NULL,			-- ORDER USER
	TOTAL_PRICE		FLOAT NOT NULL,					-- TOTAL PRICE
	OR_STATUS		VARCHAR(1) NOT NULL,			--(1:주문, 2:주문확인, 3:매장입고, 4:찾아감, 5: 취소)
	END_DATE		DATETIME,						-- 찾은 일자, 취소일자
	INDT			DATETIME DEFAULT(GETDATE())		-- CREATE DATE
)

/*
ORDER PRODUCT
*/
CREATE TABLE ORDER_PRODUCT
(
	OR_IDX		VARCHAR(10),	-- 주문번호
	PR_IDX		INT,			-- 상품번호
	QTY			INT,			-- 수량
	PRICE		FLOAT,			-- 개별가격
	INDT		DATETIME DEFAULT(GETDATE())		-- CREATE DATE
)



